/**
 * Den frusna fixturvärlden för visuella regressionstester (task-36.7).
 *
 * EN sammanhängande värld som alla visual-specs läser ur (AC 4: mockad data,
 * noll staging-beroende, stabila pixlar) — svaren har exakt EF-respons-form
 * och parsas av samma zod-scheman som skarp data (EventSchema/
 * RegistrationSchema): ett schema-brott syns som parse-fel i vyn, aldrig som
 * tyst tom rendering.
 *
 * Datum-kontraktet (AC 5): "nu" är FROZEN_NOW och all fixtur-data är daterad
 * relativt den — kommande event ligger efter, genomförda före. Formel-härledda
 * strängar (tidKvarTillEvent) är frusna litteraler: appen räknar inte om dem,
 * så pixlarna kan aldrig driva med klockan.
 *
 * Persondata är FIKTIV (inga verkliga deltagare) men realistisk i form,
 * så baselines visar vyerna som de SKA se ut.
 */

/** Fruset "nu": tisdag 2026-09-15 kl 10:00 svensk sommartid (explicit offset —
 *  parsas identiskt på Mac och linux-CI, aldrig via plattformens lokala zon). */
export const FROZEN_NOW = new Date('2026-09-15T10:00:00+02:00');

// ── Fixtur-miljön (AC 4: noll staging-beroende) ──────────────────────────
// Visual-körningens dev-server startas med DESSA värden (playwright.config:s
// webServer-gren injicerar dem; Vite låter process-env vinna över .env-filer)
// så appen binder mot den fiktiva URL:en. Varje anrop mot den interceptas —
// att den aldrig faktiskt nås är hermetik-vaktens bevis. Konstanterna bor här
// (dependency-fritt) så BÅDE config-filen och test-ramen kan läsa dem.
export const VISUAL_SUPABASE_URL = 'https://visual-fixture.supabase.co';
export const VISUAL_SUPABASE_ANON_KEY = 'visual-fixture-anon-key';

/** Skövde-eventets ID exporteras — eventsidans/anmälda-vyns specs navigerar
 *  till `/event/${VISUAL_EVENT_ID}`. */
export const VISUAL_EVENT_ID = 'recVisualEvent0001';
const EVENT_SKOVDE = VISUAL_EVENT_ID;
const EVENT_GBG = 'recVisualEvent0002';
const EVENT_VARBERG = 'recVisualEvent0003';

/** `get-events`-svaret: kommande utbildning + kommande föreläsning + genomförd. */
export const EVENTS_RESPONSE = {
  events: [
    {
      id: EVENT_SKOVDE,
      eventlabel: 'Skövde 26–27 sep',
      eventNamn: 'Utbildning Skövde',
      typ: 'Utbildning - 2 dagar',
      ort: 'Skövde',
      startdatum: '2026-09-26',
      slutdatum: '2026-09-27',
      tidKvarTillEvent: '11 dagar',
      maxPlatser: 12,
      antalAnmalda: 8,
      platserKvar: 4,
      anmaldBelaggning: 0.67,
      bekraftadBelaggning: 0.5,
      antalNyaAnmalningar: 2,
      antalAnmalningsavgifter: 4,
      antalSlutbetalningar: 2,
      antalSlutbetalningFelande: 1,
      status: 'Planerat',
      eventKey: 'Event-41',
      borOverAntal: 3,
    },
    {
      id: EVENT_GBG,
      eventlabel: 'Göteborg 9 okt',
      eventNamn: 'Föreläsning Göteborg',
      typ: 'Föreläsning',
      ort: 'Göteborg',
      startdatum: '2026-10-09',
      slutdatum: '2026-10-09',
      tidKvarTillEvent: '24 dagar',
      maxPlatser: 40,
      antalAnmalda: 17,
      platserKvar: 23,
      anmaldBelaggning: 0.43,
      bekraftadBelaggning: 0.35,
      antalNyaAnmalningar: 0,
      antalAnmalningsavgifter: 0,
      antalSlutbetalningar: 0,
      antalSlutbetalningFelande: 0,
      status: 'Planerat',
      eventKey: 'Event-42',
      borOverAntal: 0,
    },
    {
      id: EVENT_VARBERG,
      eventlabel: 'Varberg 22–23 aug',
      eventNamn: 'Utbildning Varberg',
      typ: 'Utbildning - 2 dagar',
      ort: 'Varberg',
      startdatum: '2026-08-22',
      slutdatum: '2026-08-23',
      tidKvarTillEvent: null,
      maxPlatser: 12,
      antalAnmalda: 12,
      platserKvar: 0,
      anmaldBelaggning: 1,
      bekraftadBelaggning: 1,
      antalNyaAnmalningar: 0,
      antalAnmalningsavgifter: 12,
      antalSlutbetalningar: 12,
      antalSlutbetalningFelande: 0,
      status: 'Genomfört',
      eventKey: 'Event-38',
      borOverAntal: 5,
    },
  ],
} as const;

/**
 * `get-registrations`-svaret (event-lösa grenen — Hem-aggregeringen läser den
 * utan params). Mixen är vald så dashboard-korten får innehåll: två Ny
 * anmälan-flaggade (NyaAnmalningarCard), obetalda avgifter/slutbetalningar
 * (ObetaldaCard) och en skickad betalningspåminnelse.
 */
export const REGISTRATIONS_RESPONSE = {
  registrations: [
    {
      id: 'recVisualReg000001',
      namn: 'Anna Andersson',
      fornamn: 'Anna',
      efternamn: 'Andersson',
      email: 'anna.andersson@example.se',
      telefon: '070-123 45 01',
      eventNamn: 'Utbildning Skövde',
      ort: 'Skövde',
      status: 'Obekräftad',
      flagga: 'Ny anmälan',
      anmalningsavgift: 'Ej mottagen',
      slutbetalning: 'Ej mottagen',
      betalningspaminnelseSkickad: null,
      inskickad: '2026-09-13',
      motivering: 'Vill utvecklas i mitt ledarskap.',
      tidigareErfarenhet: null,
      antalPlatser: 1,
      notering: null,
      eventId: EVENT_SKOVDE,
      personId: 'recVisualPers00001',
    },
    {
      id: 'recVisualReg000002',
      namn: 'Björn Bergström',
      fornamn: 'Björn',
      efternamn: 'Bergström',
      email: 'bjorn.bergstrom@example.se',
      telefon: '070-123 45 02',
      eventNamn: 'Utbildning Skövde',
      ort: 'Skövde',
      status: 'Obekräftad',
      flagga: 'Ny anmälan',
      anmalningsavgift: 'Ej mottagen',
      slutbetalning: 'Ej mottagen',
      betalningspaminnelseSkickad: null,
      inskickad: '2026-09-14',
      motivering: null,
      tidigareErfarenhet: 'Gick föreläsningen i våras.',
      antalPlatser: 1,
      notering: null,
      eventId: EVENT_SKOVDE,
      personId: 'recVisualPers00002',
    },
    {
      id: 'recVisualReg000003',
      namn: 'Cecilia Ceder',
      fornamn: 'Cecilia',
      efternamn: 'Ceder',
      email: 'cecilia.ceder@example.se',
      telefon: '070-123 45 03',
      eventNamn: 'Utbildning Skövde',
      ort: 'Skövde',
      status: 'Bekräftad (mail skickat)',
      flagga: 'Mottagen',
      anmalningsavgift: 'Mottagen',
      slutbetalning: 'Ej mottagen',
      betalningspaminnelseSkickad: null,
      inskickad: '2026-09-02',
      motivering: null,
      tidigareErfarenhet: null,
      antalPlatser: 1,
      notering: 'Vegetarisk kost.',
      eventId: EVENT_SKOVDE,
      personId: 'recVisualPers00003',
    },
    {
      id: 'recVisualReg000004',
      namn: 'David Dahl',
      fornamn: 'David',
      efternamn: 'Dahl',
      email: 'david.dahl@example.se',
      telefon: '070-123 45 04',
      eventNamn: 'Utbildning Skövde',
      ort: 'Skövde',
      status: 'Bekräftad (mail skickat)',
      flagga: 'Mottagen',
      anmalningsavgift: 'Mottagen',
      slutbetalning: 'Mottagen',
      betalningspaminnelseSkickad: null,
      inskickad: '2026-08-28',
      motivering: null,
      tidigareErfarenhet: null,
      antalPlatser: 2,
      notering: null,
      eventId: EVENT_SKOVDE,
      personId: 'recVisualPers00004',
    },
    {
      id: 'recVisualReg000005',
      namn: 'Emma Eklund',
      fornamn: 'Emma',
      efternamn: 'Eklund',
      email: 'emma.eklund@example.se',
      telefon: '070-123 45 05',
      eventNamn: 'Föreläsning Göteborg',
      ort: 'Göteborg',
      status: 'Bekräftad (mail skickat)',
      flagga: 'Mottagen',
      anmalningsavgift: 'Ej relevant (för föreläsningar)',
      slutbetalning: 'Ej relevant (för föreläsningar)',
      betalningspaminnelseSkickad: null,
      inskickad: '2026-09-05',
      motivering: null,
      tidigareErfarenhet: null,
      antalPlatser: 1,
      notering: null,
      eventId: EVENT_GBG,
      personId: 'recVisualPers00005',
    },
    {
      id: 'recVisualReg000006',
      namn: 'Filip Forsberg',
      fornamn: 'Filip',
      efternamn: 'Forsberg',
      email: 'filip.forsberg@example.se',
      telefon: '070-123 45 06',
      eventNamn: 'Utbildning Skövde',
      ort: 'Skövde',
      status: 'Betalningspåminnelse skickad',
      flagga: 'Mottagen',
      anmalningsavgift: 'Ej mottagen',
      slutbetalning: 'Ej mottagen',
      betalningspaminnelseSkickad: '2026-09-10',
      inskickad: '2026-08-25',
      motivering: null,
      tidigareErfarenhet: null,
      antalPlatser: 1,
      notering: null,
      eventId: EVENT_SKOVDE,
      personId: 'recVisualPers00006',
      kalla: 'Manuell',
    },
  ],
} as const;

/**
 * `get-event`-svaret (eventsidans aggregerande detalj för Skövde-eventet):
 * beläggningens innehållsmodell (task-18.2-fälten) + auto-utskicks-styrningen
 * — allt fruset mot samma värld som listsvaret.
 */
export const EVENT_DETAIL_RESPONSE = {
  event: {
    ...EVENTS_RESPONSE.events[0],
    reserverade: 2,
    manuelltTillagda: 1,
    viaFormular: 6,
    medfoljande: 1,
    vantelista: 2,
    deltagarinfoAutoAvstangt: false,
  },
} as const;

/** `get-event-notes`-svaret (eventsidans antecknings-ström, ADR-075). */
export const EVENT_NOTES_RESPONSE = {
  notes: [
    {
      id: 'recVisualNote00001',
      forfattare: 'Lotta',
      text: 'Lokalen bokad och bekräftad — samma sal som i våras.',
      tidpunkt: '2026-09-08T14:30:00.000Z',
      eventId: EVENT_SKOVDE,
    },
    {
      id: 'recVisualNote00002',
      forfattare: 'Roger',
      text: 'Fika beställd till båda dagarna.',
      tidpunkt: '2026-09-12T09:15:00.000Z',
      eventId: EVENT_SKOVDE,
    },
  ],
} as const;

/** `get-event-formats`-svaret (de två skarpa bas-formaten). */
export const EVENT_FORMATS_RESPONSE = {
  eventFormats: [
    { id: 'recVisualFormat001', namn: 'Utbildning - 2 dagar' },
    { id: 'recVisualFormat002', namn: 'Föreläsning' },
  ],
} as const;

/** `get-persons`-svaret (personlistan, en sida — nextCursor null). */
export const PERSONS_RESPONSE = {
  persons: [
    {
      id: 'recVisualPers00001',
      namn: 'Anna Andersson',
      fornamn: 'Anna',
      efternamn: 'Andersson',
      email: 'anna.andersson@example.se',
      telefon: '070-123 45 01',
      ort: ['Skövde'],
      manuellFlagga: null,
      aiFlagga: null,
      anteckningar: null,
      antalAnmalningar: 1,
      antalDeltaganden: 0,
      erfarenhetsniva: null,
      erfarenhetsbadge: null,
      senasteInteraktion: 'Anmälan Utbildning Skövde',
      senasteInteraktionDatum: '2026-09-13',
      dagarSedanSenaste: 2,
      harAktivAnmalan: 'Ja',
      ejGodkandMail: false,
      radSkapad: '2026-09-13',
      anmalningIds: ['recVisualReg000001'],
      deltagandeIds: [],
    },
    {
      id: 'recVisualPers00002',
      namn: 'Björn Bergström',
      fornamn: 'Björn',
      efternamn: 'Bergström',
      email: 'bjorn.bergstrom@example.se',
      telefon: '070-123 45 02',
      ort: ['Skövde', 'Varberg'],
      manuellFlagga: null,
      aiFlagga: null,
      anteckningar: 'Återkommande deltagare.',
      antalAnmalningar: 2,
      antalDeltaganden: 1,
      erfarenhetsniva: 'RIM 1',
      erfarenhetsbadge: 'RIM 1',
      senasteInteraktion: 'Anmälan Utbildning Skövde',
      senasteInteraktionDatum: '2026-09-14',
      dagarSedanSenaste: 1,
      harAktivAnmalan: 'Ja',
      ejGodkandMail: false,
      radSkapad: '2026-04-02',
      anmalningIds: ['recVisualReg000002'],
      deltagandeIds: ['recVisualDelt00001'],
    },
    {
      id: 'recVisualPers00003',
      namn: 'Cecilia Ceder',
      fornamn: 'Cecilia',
      efternamn: 'Ceder',
      email: 'cecilia.ceder@example.se',
      telefon: '070-123 45 03',
      ort: ['Skövde'],
      manuellFlagga: null,
      aiFlagga: null,
      anteckningar: 'Vegetarisk kost.',
      antalAnmalningar: 1,
      antalDeltaganden: 1,
      erfarenhetsniva: 'RIM 1',
      erfarenhetsbadge: 'RIM 1',
      senasteInteraktion: 'Avgift mottagen',
      senasteInteraktionDatum: '2026-09-04',
      dagarSedanSenaste: 11,
      harAktivAnmalan: 'Ja',
      ejGodkandMail: false,
      radSkapad: '2026-02-17',
      anmalningIds: ['recVisualReg000003'],
      deltagandeIds: ['recVisualDelt00002'],
    },
    {
      id: 'recVisualPers00004',
      namn: 'David Dahl',
      fornamn: 'David',
      efternamn: 'Dahl',
      email: 'david.dahl@example.se',
      telefon: '070-123 45 04',
      ort: ['Skövde'],
      manuellFlagga: null,
      aiFlagga: null,
      anteckningar: null,
      antalAnmalningar: 1,
      antalDeltaganden: 0,
      erfarenhetsniva: null,
      erfarenhetsbadge: null,
      senasteInteraktion: 'Slutbetalning mottagen',
      senasteInteraktionDatum: '2026-09-01',
      dagarSedanSenaste: 14,
      harAktivAnmalan: 'Ja',
      ejGodkandMail: false,
      radSkapad: '2026-08-28',
      anmalningIds: ['recVisualReg000004'],
      deltagandeIds: [],
    },
    {
      id: 'recVisualPers00005',
      namn: 'Emma Eklund',
      fornamn: 'Emma',
      efternamn: 'Eklund',
      email: 'emma.eklund@example.se',
      telefon: '070-123 45 05',
      ort: ['Göteborg'],
      manuellFlagga: null,
      aiFlagga: null,
      anteckningar: null,
      antalAnmalningar: 1,
      antalDeltaganden: 2,
      erfarenhetsniva: 'RIM 2',
      erfarenhetsbadge: 'RIM 2',
      senasteInteraktion: 'Anmälan Föreläsning Göteborg',
      senasteInteraktionDatum: '2026-09-05',
      dagarSedanSenaste: 10,
      harAktivAnmalan: 'Ja',
      ejGodkandMail: false,
      radSkapad: '2025-11-20',
      anmalningIds: ['recVisualReg000005'],
      deltagandeIds: ['recVisualDelt00003', 'recVisualDelt00004'],
    },
    {
      id: 'recVisualPers00006',
      namn: 'Filip Forsberg',
      fornamn: 'Filip',
      efternamn: 'Forsberg',
      email: 'filip.forsberg@example.se',
      telefon: '070-123 45 06',
      ort: ['Skövde'],
      manuellFlagga: 'Följ upp betalning',
      aiFlagga: null,
      anteckningar: null,
      antalAnmalningar: 1,
      antalDeltaganden: 0,
      erfarenhetsniva: null,
      erfarenhetsbadge: null,
      senasteInteraktion: 'Betalningspåminnelse skickad',
      senasteInteraktionDatum: '2026-09-10',
      dagarSedanSenaste: 5,
      harAktivAnmalan: 'Ja',
      ejGodkandMail: false,
      radSkapad: '2026-08-25',
      anmalningIds: ['recVisualReg000006'],
      deltagandeIds: [],
    },
    {
      id: 'recVisualPers00007',
      namn: 'Gunilla Granqvist',
      fornamn: 'Gunilla',
      efternamn: 'Granqvist',
      email: 'gunilla.granqvist@example.se',
      telefon: '070-123 45 07',
      ort: ['Varberg'],
      manuellFlagga: null,
      aiFlagga: null,
      anteckningar: null,
      antalAnmalningar: 1,
      antalDeltaganden: 3,
      erfarenhetsniva: 'RIM 2',
      erfarenhetsbadge: 'RIM 2',
      senasteInteraktion: 'Deltagande Utbildning Varberg',
      senasteInteraktionDatum: '2026-08-23',
      dagarSedanSenaste: 23,
      harAktivAnmalan: null,
      ejGodkandMail: false,
      radSkapad: '2025-05-12',
      anmalningIds: ['recVisualReg000007'],
      deltagandeIds: ['recVisualDelt00005', 'recVisualDelt00006', 'recVisualDelt00007'],
    },
    {
      id: 'recVisualPers00008',
      namn: 'Hassan Haddad',
      fornamn: 'Hassan',
      efternamn: 'Haddad',
      email: 'hassan.haddad@example.se',
      telefon: '070-123 45 08',
      ort: [],
      manuellFlagga: null,
      aiFlagga: 'Trolig lead',
      anteckningar: 'Fyllde i intresseformuläret i somras.',
      antalAnmalningar: 0,
      antalDeltaganden: 0,
      erfarenhetsniva: null,
      erfarenhetsbadge: null,
      senasteInteraktion: 'Intresseanmälan',
      senasteInteraktionDatum: '2026-07-30',
      dagarSedanSenaste: 47,
      harAktivAnmalan: null,
      ejGodkandMail: true,
      radSkapad: '2026-07-30',
      anmalningIds: [],
      deltagandeIds: [],
    },
  ],
  nextCursor: null,
} as const;
